// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFOLnNvYFlERfnt0NoWq2eZn6DTFMuJ34',
    appId: '1:347894837878:web:1d3f5c1ee2d3813436e557',
    messagingSenderId: '347894837878',
    projectId: 'advert-8c626',
    authDomain: 'advert-8c626.firebaseapp.com',
    storageBucket: 'advert-8c626.appspot.com',
    measurementId: 'G-9E8H6CLNJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTLao_GC9LoYp7uec_KlzOjfZOPffbwlg',
    appId: '1:347894837878:android:73fd74d1f095470336e557',
    messagingSenderId: '347894837878',
    projectId: 'advert-8c626',
    storageBucket: 'advert-8c626.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnkl3XlxFx-10finCapOxyqit9hDRx_yg',
    appId: '1:347894837878:ios:bdc749f52ec4bd3036e557',
    messagingSenderId: '347894837878',
    projectId: 'advert-8c626',
    storageBucket: 'advert-8c626.appspot.com',
    iosClientId: '347894837878-ja4rssj7omutmmbeadr56vn8lipc7o3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.advert',
  );
}
